### ISSUE TITLE
to_proc_icky! shouldn't be a 10 on ruby 1.9+

### ISSUE THREAD

**Issue by JohnAmican** [seattlerb/flog#21]
I'm assuming this score was given because of the performance hit you used to get in 1.8 for doing something like `["1", "2", "3", "4"].map(&:to_i)` vs. `["1", "2", "3", "4"].map { |n| n.to_i }`.

Can we at least make this score conditional based on what version of Ruby is running flog?

**Comment by mainameiz** [comment]
It's been a while... but `map(&:to_i)` still gets more points on flog 4.6.4 🙂 

@zenspider could you please clarify your position about these two examples and why the second one gets more points than first:

1) `['1', '2', '3', '4'].map{ |n| n.to_i } => 2.3 points`
2) `['1', '2', '3', '4'].map(&:to_i)       => 3.4 points`

As for me, they should get the same points.

If you say it must be changed - I will make a PR.

**Comment by zenspider** [comment]
@mainameiz it gets `:to_proc_normal` which in today's world (not counting ruby 3) is worth 1. Seems reasonable to me.

> As for me, they should get the same points.

well, they don't. They're not the same. Here's what flog sees/does:

```ruby
s(:iter,
  s(:call, RECV, :map),
  s(:args, :n),
  s(:call, s(:lvar, :n), :to_i))

# 2.5: main#f                           to_proc.rb:1-2
# 1.2:   to_i
# 1.1:   branch
# 1.1:   map

s(:call, RECV, :map, s(:block_pass, s(:lit, :to_i)))

# 3.7: main#g                           to_proc.rb:5-6
# 1.3:   block_pass
# 1.3:   to_proc_normal
# 1.1:   map
```

**Comment by zenspider** [comment]
This is 7 years dead. I'm locking it down. Please file a new issue if need be.
