### ISSUE TITLE
Test does not run on ruby 2.2.0

### ISSUE THREAD

**Issue by teoljungberg** [seattlerb/flog#51]
But they pass just fine on ruby `2.1.X` and lower.
What seems to be the culprit is: https://github.com/seattlerb/flog/blob/01c7f73c5ec2cbc5f0f181ee1d83f05bcd96747e/test/test_flog.rb#L135-139

Tho I can't really understand what the case-statement really does, hence not submit a PR to fix it.

**Comment by zenspider** [comment]
Fixed. Thanks!
