### ISSUE TITLE
Error with {"key":value} syntax

### ISSUE THREAD

**Issue by posgarou** [seattlerb/flog#53]
As of Ruby 2.2.0, hash key strings can be followed by a colon in the declaration, e.g. `{'key': true}`.  https://github.com/ruby/ruby/blob/v2_2_0/NEWS

```
* Hash literal
  * Symbol key followed by a colon can be quoted. [Feature #4276]
```

Flog bugs out on this new syntax, however, with the following error: `/ruby-2.2.0/lib/ruby/2.2.0/racc/parser.rb:527:in 'on_error': app/helpers/button_helper.rb:2 :: parse error on value ":" (tCOLON) (Racc::ParseError)`.

**Comment by zenspider** [comment]
This is actually a bug in ruby_parser.

**Comment by zenspider** [comment]
Can you file this on ruby_parser so it is easier for me to organize and plan? Thanks. Closing.
