### ISSUE TITLE
Average precission

### ISSUE THREAD

**Issue by scooler** [seattlerb/flog#58]
Flog nicely points out the worst code (or very good candidates :D), but for use as a tool, for feedback how are you doing over time, it would be great if the average was more precise. One decimal place isn't precise enough for a big code base.

 I was thinking that it'd be best to make this configurable from the command line. I'm not sure if the whole thing (how the results are displayed), or just the average's decimal places. I guess that'd be simplest - I don't see use in changing the rest. So `-d` is taken, `-p` `--precision` ?

It's all done at the end of `flog_cli.rb` and done locally it all works, but the repo doesn't include the the .gemspec, why ?

**Comment by zenspider** [comment]
Do you just mean the `flog/method` part of the report? I've always found that the troublesome projects usually follow a power curve so extra levels of precision don't help. For non-troublesome projects, well... you're already out of trouble. :)

My only concern is that adding extra precision makes the report not line up and is uglier.

**Comment by zenspider** [comment]
Can you mock up some output how you'd like to see it?

**Comment by scooler** [comment]
I actually don't understand what do you mean by "follow a power curve" - and I'm not even sure if the extra precision will help. I just felt frustrated not knowing/seeing the changes :). Both ways actually - could be used as an argument for "HEY - FIX THAT" or "Yes - that's the way to go"

As far as output a quick thing that I whipped up [here](https://github.com/scooler/flog) shows like this:
```
   941.6: flog total
  15.694: flog/method average

   131.9: FlogGauntlet#display_report      lib/gauntlet_flog.rb:32
    37.5:   branch
    33.5:   assignment
```

as opposed to

```
   941.6: flog total
    15.7: flog/method average

   131.9: FlogGauntlet#display_report      lib/gauntlet_flog.rb:32
    37.5:   branch
    33.5:   assignment
```

Perhaps less beautiful, but IMHO more satisfying :+1:

**Comment by scooler** [comment]
@zenspider So - is it OK - I mean - should I make a pull request ? or it's not worth having ?

**Comment by zenspider** [comment]
`15.7−15.694=0.006`. I just don't think that teeny extra bit of information is really that useful in deciding anything, and it is noticeably uglier. Sorry. I just don't think this does that much to warrant a change.

**Comment by scooler** [comment]
That's obviously an example, right - it could mean difference of 0.049 I guess :). Thing is the average changes rather slowly - often by ~0.020 - I figured it's a good thing seeing those changes as they go along - have some "tangible" proof of quality increase/decrease - apart from "my habits are like this and mine are like that ;)

Anyway - I've taken into account possibility that it wouldn't meet your standards, so I've made it as a uniq subversion. 
So I guess if there is no point in adding it you can close the issue :)
Happy New Year :+1: :)

**Comment by zenspider** [comment]
I would try to track total over time. Average per method is an ok metric to know if you need to break things up, but it says little about the system as a whole.

Seeing the power curve over time would also be a fantastic visualization. Maybe I'll try to figure that one out.
