### ISSUE TITLE
Rake task behavior seems counter-intuitive

### ISSUE THREAD

**Issue by jasonkarns** [seattlerb/flog#59]
I pulled in flog and added the rake task (defaults), ran `rake flog` and got: `Score is too high!` error, without any report.

I would have expected the default rake task to be identical to running flog against the same directories as specified in the rake task (app bin lib spec test).

What is the intention of raising an exception when over the threshold?

But most importantly, why is the report hidden behind `--trace`? The report is literally the only reason I want to run flog, but I have to run rake in tracing mode to get it? Am I missing something? I'd rather not have to see all of rake's trace output just so I can get the flog report.

I'm more than happy to submit a PR to make the rake task more "intuitive" (for some definition of intuitive), but I think I might be missing something in the author's intentions.

**Comment by zenspider** [comment]
Too many issues in one ticket.

1. The intention of raising when over a threshold is to allow people to put limits on their projects and have them enforced via rake.

2. The rake task is meant to be part of a build system (or CI, or whatever). The output is noise so it is off by default.

3. If you want a report on your code, why not just run flog straight up?

4. Happy to take a PR to make it more intuitive, as long as it is intuitive to ME. :)

**Comment by zenspider** [comment]
Anything?

**Comment by zenspider** [comment]
No response. Closing.
