### ISSUE TITLE
Flog on python

### ISSUE THREAD

**Issue by xero88** [seattlerb/flog#69]
Hi,

First, thank you for you nice lib, I'm using it through Rubycritic, and it's great tool to follow evolution of code quality of a projet.

My question is : do you know something equivalent to Python ?

**Comment by zenspider** [comment]
I don't. Sorry. I haven't touched python in ages. It shouldn't be too hard to do tho. I know from my work on codeclimate that there's good python parsers available. You could even theoretically make flog work with it (flay is multi-lingual and flog could be too).
