### ISSUE TITLE
stdin processing broken

### ISSUE THREAD

**Issue by olbrich** [seattlerb/flog#71]
Sometime between version 4.6.2 and 4.6.4 stdin handling broke. This could be related to `path_expander` which also went from 1.0.5 to 1.1.0.

Original behavior...

```bash
$ echo "def test; end" | flog -s
0.0: flog total
0.0: flog/method average
```

Would just read from stdin.

New behavior...
```bash
$ echo "def test; end" | flog -s
171338.0: flog total
    11.7: flog/method average
```
Appears to ignore stdin and just use the default glob of "**/*.{rb,rake}" instead. This is also true when..

```bash
$ echo "def test; end" | flog -s - 
171338.0: flog total
    11.7: flog/method average
```

**Comment by zenspider** [comment]
Yeah. I've been bit by this recently...

**Comment by mileslane** [comment]
Any resolution for this?

**Comment by mileslane** [comment]
ping?

**Comment by zenspider** [comment]
Fixed. Update path_expander.
