### ISSUE TITLE
Crash with hash as block

### ISSUE THREAD

**Issue by t-kinoshita** [seattlerb/flog#73]
```rb
Foo.new(
  :bar,
  &{ hoge: :piyo }
)
```

Above valid code (`Hash` has `#to_proc` since Ruby 2.3) produces following `RuntimeError`.

```
/path/to/ruby/gems/2.5.0/gems/flog-4.6.4/lib/flog.rb:381:in `process_block_pass': {:block_pass_even_ickier!=>s(:hash, s(:lit, :hoge), s(:lit, :piyo))} (RuntimeError)
```

* flog version: 4.6.4
* Ruby version: `ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]`
* `uname -a`:  `Linux (machine name omitted) 2.6.32-754.31.1.el6.x86_64 #1 SMP Wed Jul 15 16:02:21 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by zenspider** [comment]
That's disguisting tbfh

**Comment by zenspider** [comment]
This is fixed and will go out in the next release.
